#include "test_support.hpp"

#include "ipi/v2x/j2735_ipi_regional_codec.hpp"

#include <cmath>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

std::vector<std::uint8_t> from_hex(const std::string& hex) {
    if ((hex.size() % 2U) != 0U) throw std::invalid_argument("odd hex string");
    std::vector<std::uint8_t> bytes;
    bytes.reserve(hex.size() / 2U);
    for (std::size_t index = 0; index < hex.size(); index += 2U) {
        bytes.push_back(static_cast<std::uint8_t>(
            std::stoul(hex.substr(index, 2U), nullptr, 16)));
    }
    return bytes;
}

template <typename Callable>
bool rejects(Callable&& callable) {
    try {
        callable();
    } catch (const std::exception&) {
        return true;
    }
    return false;
}

ipi::CooperativeServiceMessage make_perception_message() {
    ipi::CooperativeServiceMessage message;
    message.sessionId[0] = 0x42;
    message.vehicleId = {'c', 'a', 'v', '-', '1'};
    message.serviceClass = ipi::ServiceClass::GuidedPerception;
    message.guidanceStatus = ipi::GuidanceStatus::Update;
    message.confidence = 96;

    ipi::DetectedObject object;
    object.objectId = {0x10, 0x20, 0x30, 0x40};
    object.classification = ipi::DetectedObject::Classification::Pedestrian;
    object.position.latitude = 42.3314271;
    object.position.longitude = -83.0457538;
    object.velocityMps = 1.42;

    ipi::GuidedPerceptionPayload perception;
    perception.detectedObjects.push_back(object);
    message.perception = perception;
    return message;
}

ipi::CooperativeServiceMessage make_planning_message() {
    ipi::CooperativeServiceMessage message;
    message.sessionId = {0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
                         0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff};
    message.vehicleId = {'v', 'e', 'h', '-', 'p', 'l', 'a', 'n'};
    message.serviceClass = ipi::ServiceClass::GuidedPlanning;
    message.guidanceStatus = ipi::GuidanceStatus::Request;
    message.requestedHorizonMs = 5000;
    message.confidence = 88;
    message.expirationTimeDs = 0x12345678U;

    ipi::Waypoint first;
    first.position.latitude = 42.3000000;
    first.position.longitude = -83.0000000;
    first.position.elevation = 182.4;
    first.targetSpeedMps = 12.34;
    first.dwellTimeMs = 1000;

    ipi::Waypoint second;
    second.position.latitude = 42.3000100;
    second.position.longitude = -83.0000100;

    ipi::GuidedPlanningPayload planning;
    planning.fallbackRoute = true;
    planning.waypoints = {first, second};
    message.planning = planning;
    message.offloadPayload = std::vector<std::uint8_t>{0xde, 0xad, 0xbe, 0xef, 0x00};
    message.offloadTaskId = "task-17";
    return message;
}

ipi::CooperativeServiceMessage make_control_message() {
    ipi::CooperativeServiceMessage message;
    message.sessionId.fill(0xff);
    message.vehicleId = {'c', 't', 'r', 'l'};
    message.serviceClass = ipi::ServiceClass::GuidedControl;
    message.guidanceStatus = ipi::GuidanceStatus::Complete;
    message.confidence = 100;

    ipi::GuidedControlPayload control;
    control.commands = {
        {ipi::ControlCommand::Axis::Steering, -1000},
        {ipi::ControlCommand::Axis::Throttle, 500},
        {ipi::ControlCommand::Axis::Brake, 0},
    };
    message.control = control;
    return message;
}

ipi::CooperativeServiceMessage make_minimal_message() {
    ipi::CooperativeServiceMessage message;
    message.vehicleId = {'x'};
    message.serviceClass = ipi::ServiceClass::GuidedPlanning;
    message.guidanceStatus = ipi::GuidanceStatus::Request;
    return message;
}

} // namespace

int main() {
    return ipi::tests::run_test("j2735_ipi_regional_codec", [] {
        const ipi::v2x::J2735IpiRegionalCodec codec;
        const auto message = make_perception_message();

        // Independently generated by asn1tools 0.167.0 and pycrate 0.7.11
        // from cpp/asn1/IPI.asn. The outer frame was generated with USDOT's
        // J2735 202409 pycrate package using TestMessage00 and unknown region
        // passthrough, which is bit-compatible with the SEP2023 structure.
        const auto expectedRegional = from_hex(
            "2800840000000000000000000000000000008c6c2ec5a62b81031020304053b8"
            "0b17ce7282cfa0238000");
        const auto expectedFrame = from_hex(
            "00f02d3905450010800000000000000000000000000000118d85d8b4c5702062"
            "0406080a770162f9ce5059f404700000");

        const auto planningFrame = from_hex(
            "00f04c39092fc00004488cd115599de2266aaef3377bbfddd995a0b5c1b185b8"
            "04e22c091a2b3c107cedb60c039d106800a72004d20fa04edb612439d1061c005"
            "deadbeef00067461736b2d3137000");
        const auto controlFrame = from_hex(
            "00f0213903c5003fffffffffffffffffffffffffffffffcd8dd1c9b2b2440006ee"
            "4fa000");
        const auto minimalFrame = from_hex(
            "00f017390280000000000000000000000000000000000001e000");

        const auto regional = codec.encode_regional_value(message);
        ipi::tests::expect(regional == expectedRegional,
                           "IPI regional value must match both independent ASN.1 encoders");
        const auto frame = codec.encode_message_frame(message);
        ipi::tests::expect(frame == expectedFrame,
                           "IPI MessageFrame must match the independent J2735 reference vector");

        const auto decoded = codec.decode_message_frame(frame);
        ipi::tests::expect(decoded.sessionId == message.sessionId &&
                               decoded.vehicleId == message.vehicleId &&
                               decoded.serviceClass == message.serviceClass &&
                               decoded.guidanceStatus == message.guidanceStatus &&
                               decoded.confidence == message.confidence,
                           "IPI MessageFrame identity and status should round-trip");
        ipi::tests::expect(decoded.perception &&
                               decoded.perception->detectedObjects.size() == 1U,
                           "IPI perception payload should round-trip");
        const auto& decodedObject = decoded.perception->detectedObjects.front();
        ipi::tests::expect(decodedObject.objectId ==
                                   message.perception->detectedObjects.front().objectId &&
                               decodedObject.classification ==
                                   ipi::DetectedObject::Classification::Pedestrian &&
                               std::fabs(decodedObject.position.latitude - 42.3314271) < 0.0000001 &&
                               std::fabs(decodedObject.position.longitude + 83.0457538) < 0.0000001 &&
                               decodedObject.velocityMps &&
                               std::fabs(*decodedObject.velocityMps - 1.42) < 0.01,
                           "IPI fixed-point object fields should preserve schema resolution");

        ipi::tests::expect(codec.decode_regional_value(regional).vehicleId == message.vehicleId,
                           "standalone IPI regional value should decode");

        const auto planning = make_planning_message();
        ipi::tests::expect(codec.encode_message_frame(planning) == planningFrame,
                           "planning and all optional fields should match independent vectors");
        const auto decodedPlanning = codec.decode_message_frame(planningFrame);
        ipi::tests::expect(decodedPlanning.planning &&
                               decodedPlanning.planning->waypoints.size() == 2U &&
                               decodedPlanning.planning->fallbackRoute &&
                               decodedPlanning.offloadPayload == planning.offloadPayload &&
                               decodedPlanning.offloadTaskId == planning.offloadTaskId &&
                               decodedPlanning.expirationTimeDs == planning.expirationTimeDs,
                           "planning and offload optionals should round-trip");

        const auto control = make_control_message();
        ipi::tests::expect(codec.encode_message_frame(control) == controlFrame,
                           "control fields should match independent vectors");
        const auto decodedControl = codec.decode_message_frame(controlFrame);
        ipi::tests::expect(decodedControl.control &&
                               decodedControl.control->commands.size() == 3U &&
                               decodedControl.control->commands.front().valuePermille == -1000 &&
                               decodedControl.control->commands.back().axis ==
                                   ipi::ControlCommand::Axis::Brake,
                           "signed control commands should round-trip");

        const auto minimal = make_minimal_message();
        ipi::tests::expect(codec.encode_message_frame(minimal) == minimalFrame,
                           "minimal request should match independent vectors");
        const auto decodedMinimal = codec.decode_message_frame(minimalFrame);
        ipi::tests::expect(!decodedMinimal.planning && !decodedMinimal.perception &&
                               !decodedMinimal.control && !decodedMinimal.confidence,
                           "minimal request should preserve absent optionals");

        auto wrongMessageId = frame;
        wrongMessageId[1] ^= 0x01U;
        ipi::tests::expect(rejects([&] { (void)codec.decode_message_frame(wrongMessageId); }),
                           "a non-TestMessage00 MessageFrame should be rejected");

        ipi::v2x::J2735IpiRegionalProfile alternateProfile;
        alternateProfile.regionId = 201;
        const ipi::v2x::J2735IpiRegionalCodec alternateCodec(alternateProfile);
        const auto wrongRegion = alternateCodec.encode_message_frame(message);
        ipi::tests::expect(rejects([&] { (void)codec.decode_message_frame(wrongRegion); }),
                           "a different local RegionId should be rejected");

        auto nonZeroPadding = frame;
        nonZeroPadding.back() |= 0x01U;
        ipi::tests::expect(rejects([&] { (void)codec.decode_message_frame(nonZeroPadding); }),
                           "non-zero UPER padding should be rejected");

        auto extendedFrame = frame;
        extendedFrame.front() |= 0x80U;
        ipi::tests::expect(rejects([&] { (void)codec.decode_message_frame(extendedFrame); }),
                           "unknown MessageFrame extensions should be rejected");

        auto truncated = frame;
        truncated.pop_back();
        ipi::tests::expect(rejects([&] { (void)codec.decode_message_frame(truncated); }),
                           "truncated IPI MessageFrame should be rejected");

        auto invalidCoordinate = message;
        invalidCoordinate.perception->detectedObjects.front().position.latitude = 91.0;
        ipi::tests::expect(rejects([&] { (void)codec.encode_message_frame(invalidCoordinate); }),
                           "coordinates outside the ASN.1 range should be rejected");

        auto oversizedOffload = message;
        oversizedOffload.perception.reset();
        oversizedOffload.serviceClass = ipi::ServiceClass::GuidedPlanning;
        oversizedOffload.offloadPayload = std::vector<std::uint8_t>(2049U, 0x5aU);
        ipi::tests::expect(rejects([&] { (void)codec.encode_message_frame(oversizedOffload); }),
                           "offload payloads above the formal profile limit should be rejected");

        ipi::v2x::J2735IpiRegionalProfile registeredRegion;
        registeredRegion.regionId = 3;
        ipi::tests::expect(
            rejects([&] { (void)ipi::v2x::J2735IpiRegionalCodec(registeredRegion); }),
            "IPI must not silently use a registered J2735 RegionId");
    });
}
